### ISSUE TITLE
Error after importing all the data

### ISSUE THREAD

**Issue by Emze100** [pookjw/CustomSPCDetent#1]
Can you describe how you add this to a different project? I finally found this answer but don't really get how to use it. I imported all the files but I get the error "Type 'UISheetPresentationController.Detent' has no member '_detent'".

**Comment by pookjw** [comment]
1. Create Objective-C Bridging Header. https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift or https://stackoverflow.com/a/28486246/17473716
2. In Objective-C Bridging Header file, fill like [this.](https://github.com/pookjw/CustomSPCDetent/blob/main/CustomSPCDetent/CustomSPCDetent-Bridging-Header.h)

**Comment by Emze100** [comment]
Brilliant! Thank you a lot!
